### ISSUE TITLE
Not an actual issue

### ISSUE THREAD

**Issue by MaterousApps** [Altpapier/SkyHelperAPI#6]
I couldn't find another way to contact you directly, figured this might be a good option. I'm not sure if you're aware of this, but someone else on GitHub is putting out 4 identical mods (suspiciously look like RATs) under your name. They tried to get me to download one and made sure I knew it was an AltPapier mod, but couldn't tell me where they got it. All 4 mods have the exact same size, and from what I could tell at a cursory glance, the exact same folder structure within the .jar file. I didn't do a deep dive into them though. I didn't want them on my PC longer than needed.

https://github.com/AltPapierMods

**Comment by Altpapier** [comment]
most likely a rat I have no idea who tries to impersonate me there but I highly recommend not downloading anything from their repos

**Comment by Altpapier** [comment]
also reported his profile to github will see what happens
